### ISSUE TITLE
Cannot running server after generate project

### ISSUE THREAD

**Issue by luffynas** [Ansvia/mainframe.rf#20]
➜  ~ cargo -V
`cargo 1.40.0 (bc8e4c8be 2019-11-22)`
➜  ~ rustc -V
`rustc 1.40.0 (73528e339 2019-12-16)`

Error:
```
➜  social-media cargo run --bin social_media_server
    Updating crates.io index
   Compiling libc v0.2.81
   Compiling autocfg v1.0.1
   Compiling cfg-if v0.1.10
   Compiling lazy_static v1.4.0
   Compiling byteorder v1.3.4
   Compiling proc-macro2 v1.0.24
   Compiling unicode-xid v0.2.1
   Compiling cfg-if v1.0.0
   Compiling syn v1.0.57
   Compiling memchr v2.3.4
   Compiling log v0.4.11
   Compiling rand_core v0.4.2
   Compiling either v1.6.1
   Compiling typenum v1.12.0
   Compiling semver-parser v0.7.0
   Compiling maybe-uninit v2.0.0
   Compiling fnv v1.0.7
   Compiling futures v0.1.30
   Compiling scopeguard v1.1.0
   Compiling serde v1.0.118
   Compiling encoding_index_tests v0.1.4
   Compiling autocfg v0.1.7
   Compiling slab v0.4.2
   Compiling regex-syntax v0.6.21
   Compiling adler v0.2.3
   Compiling cc v1.0.66
   Compiling failure_derive v0.1.8
   Compiling gimli v0.23.0
   Compiling rustc-demangle v0.1.18
   Compiling object v0.22.0
   Compiling bitflags v1.2.1
   Compiling version_check v0.1.5
   Compiling version_check v0.9.2
   Compiling tinyvec_macros v0.1.0
   Compiling ryu v1.0.5
   Compiling matches v0.1.8
   Compiling getrandom v0.1.16
   Compiling percent-encoding v1.0.1
   Compiling serde_derive v1.0.118
   Compiling proc-macro2 v0.4.30
   Compiling subtle v2.4.0
error[E0210]: type parameter `T` must be used as the type parameter for some local type (e.g., `MyStruct<T>`)
   --> /Users/uname/.cargo/registry/src/github.com-1ecc6299db9ec823/subtle-2.4.0/src/lib.rs:513:6
    |
513 | impl<T> From<CtOption<T>> for Option<T> {
    |      ^ type parameter `T` must be used as the type parameter for some local type
    |
    = note: only traits defined in the current crate can be implemented for a type parameter

error: aborting due to previous error

For more information about this error, try `rustc --explain E0210`.
error: could not compile `subtle`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by andriest** [comment]
**Minimum Supported Rust Version**
Rust 1.41 or higher.

Minimum supported Rust version can be changed in the future, but it will be done with a minor version bump.

Please check https://crates.io/crates/subtle.

**Comment by luffynas** [comment]
This issue was Resolve after upgrade Rust to 1.49.0 (e1884a8e3 2020-12-29)
